AsciiComments:
  Enabled: false
LineLength:
  Max: 140
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/FormatString:
  EnforcedStyle: percent
Documentation:
  Enabled: false
Style/Lambda:
  Enabled: false
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
Style/EmptyMethod:
  EnforcedStyle: expanded
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/Documentation:
  Enabled: false
